/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as VEventIdRouteImport } from './routes/v/$eventId'
import { Route as UUserIdRouteImport } from './routes/u/$userId'
import { Route as PListIdRouteImport } from './routes/p/$listId'

const NewIndexLazyRouteImport = createFileRoute('/new/')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewIndexLazyRoute = NewIndexLazyRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/new/index.lazy').then((d) => d.Route))
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const VEventIdRoute = VEventIdRouteImport.update({
  id: '/v/$eventId',
  path: '/v/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PListIdRoute = PListIdRouteImport.update({
  id: '/p/$listId',
  path: '/p/$listId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$listId': typeof PListIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/v/$eventId': typeof VEventIdRoute
  '/search': typeof SearchIndexRoute
  '/new': typeof NewIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$listId': typeof PListIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/v/$eventId': typeof VEventIdRoute
  '/search': typeof SearchIndexRoute
  '/new': typeof NewIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$listId': typeof PListIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/v/$eventId': typeof VEventIdRoute
  '/search/': typeof SearchIndexRoute
  '/new/': typeof NewIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p/$listId'
    | '/u/$userId'
    | '/v/$eventId'
    | '/search'
    | '/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/p/$listId' | '/u/$userId' | '/v/$eventId' | '/search' | '/new'
  id:
    | '__root__'
    | '/'
    | '/p/$listId'
    | '/u/$userId'
    | '/v/$eventId'
    | '/search/'
    | '/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PListIdRoute: typeof PListIdRoute
  UUserIdRoute: typeof UUserIdRoute
  VEventIdRoute: typeof VEventIdRoute
  SearchIndexRoute: typeof SearchIndexRoute
  NewIndexLazyRoute: typeof NewIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/': {
      id: '/new/'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$eventId': {
      id: '/v/$eventId'
      path: '/v/$eventId'
      fullPath: '/v/$eventId'
      preLoaderRoute: typeof VEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$listId': {
      id: '/p/$listId'
      path: '/p/$listId'
      fullPath: '/p/$listId'
      preLoaderRoute: typeof PListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PListIdRoute: PListIdRoute,
  UUserIdRoute: UUserIdRoute,
  VEventIdRoute: VEventIdRoute,
  SearchIndexRoute: SearchIndexRoute,
  NewIndexLazyRoute: NewIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
