/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as NewIndexRouteImport } from './routes/new/index'
import { Route as FaqIndexRouteImport } from './routes/faq/index'
import { Route as ConfigurarionIndexRouteImport } from './routes/configurarion/index'
import { Route as VEventIdRouteImport } from './routes/v/$eventId'
import { Route as UUserIdRouteImport } from './routes/u/$userId'
import { Route as PNewRouteImport } from './routes/p/new'
import { Route as PListIdRouteImport } from './routes/p/$listId'
import { Route as UUserIdEditRouteImport } from './routes/u_/$userId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewIndexRoute = NewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqIndexRoute = FaqIndexRouteImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurarionIndexRoute = ConfigurarionIndexRouteImport.update({
  id: '/configurarion/',
  path: '/configurarion/',
  getParentRoute: () => rootRouteImport,
} as any)
const VEventIdRoute = VEventIdRouteImport.update({
  id: '/v/$eventId',
  path: '/v/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PNewRoute = PNewRouteImport.update({
  id: '/p/new',
  path: '/p/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PListIdRoute = PListIdRouteImport.update({
  id: '/p/$listId',
  path: '/p/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdEditRoute = UUserIdEditRouteImport.update({
  id: '/u_/$userId/edit',
  path: '/u/$userId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$listId': typeof PListIdRoute
  '/p/new': typeof PNewRoute
  '/u/$userId': typeof UUserIdRoute
  '/v/$eventId': typeof VEventIdRoute
  '/configurarion': typeof ConfigurarionIndexRoute
  '/faq': typeof FaqIndexRoute
  '/new': typeof NewIndexRoute
  '/search': typeof SearchIndexRoute
  '/terms': typeof TermsIndexRoute
  '/u/$userId/edit': typeof UUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$listId': typeof PListIdRoute
  '/p/new': typeof PNewRoute
  '/u/$userId': typeof UUserIdRoute
  '/v/$eventId': typeof VEventIdRoute
  '/configurarion': typeof ConfigurarionIndexRoute
  '/faq': typeof FaqIndexRoute
  '/new': typeof NewIndexRoute
  '/search': typeof SearchIndexRoute
  '/terms': typeof TermsIndexRoute
  '/u/$userId/edit': typeof UUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$listId': typeof PListIdRoute
  '/p/new': typeof PNewRoute
  '/u/$userId': typeof UUserIdRoute
  '/v/$eventId': typeof VEventIdRoute
  '/configurarion/': typeof ConfigurarionIndexRoute
  '/faq/': typeof FaqIndexRoute
  '/new/': typeof NewIndexRoute
  '/search/': typeof SearchIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/u_/$userId/edit': typeof UUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p/$listId'
    | '/p/new'
    | '/u/$userId'
    | '/v/$eventId'
    | '/configurarion'
    | '/faq'
    | '/new'
    | '/search'
    | '/terms'
    | '/u/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/p/$listId'
    | '/p/new'
    | '/u/$userId'
    | '/v/$eventId'
    | '/configurarion'
    | '/faq'
    | '/new'
    | '/search'
    | '/terms'
    | '/u/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/p/$listId'
    | '/p/new'
    | '/u/$userId'
    | '/v/$eventId'
    | '/configurarion/'
    | '/faq/'
    | '/new/'
    | '/search/'
    | '/terms/'
    | '/u_/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PListIdRoute: typeof PListIdRoute
  PNewRoute: typeof PNewRoute
  UUserIdRoute: typeof UUserIdRoute
  VEventIdRoute: typeof VEventIdRoute
  ConfigurarionIndexRoute: typeof ConfigurarionIndexRoute
  FaqIndexRoute: typeof FaqIndexRoute
  NewIndexRoute: typeof NewIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  UUserIdEditRoute: typeof UUserIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/': {
      id: '/new/'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/': {
      id: '/faq/'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurarion/': {
      id: '/configurarion/'
      path: '/configurarion'
      fullPath: '/configurarion'
      preLoaderRoute: typeof ConfigurarionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$eventId': {
      id: '/v/$eventId'
      path: '/v/$eventId'
      fullPath: '/v/$eventId'
      preLoaderRoute: typeof VEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/new': {
      id: '/p/new'
      path: '/p/new'
      fullPath: '/p/new'
      preLoaderRoute: typeof PNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$listId': {
      id: '/p/$listId'
      path: '/p/$listId'
      fullPath: '/p/$listId'
      preLoaderRoute: typeof PListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u_/$userId/edit': {
      id: '/u_/$userId/edit'
      path: '/u/$userId/edit'
      fullPath: '/u/$userId/edit'
      preLoaderRoute: typeof UUserIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PListIdRoute: PListIdRoute,
  PNewRoute: PNewRoute,
  UUserIdRoute: UUserIdRoute,
  VEventIdRoute: VEventIdRoute,
  ConfigurarionIndexRoute: ConfigurarionIndexRoute,
  FaqIndexRoute: FaqIndexRoute,
  NewIndexRoute: NewIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  UUserIdEditRoute: UUserIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
